// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/use_cases/user/init.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	gomock "github.com/golang/mock/gomock"
	entities "github.com/napapol-dev-group/poc-golang/app/entities"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// RegisterUser mocks base method
func (m *MockUseCase) RegisterUser(operateAreaEntity entities.CreateUser) (*entities.CreateUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", operateAreaEntity)
	ret0, _ := ret[0].(*entities.CreateUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser
func (mr *MockUseCaseMockRecorder) RegisterUser(operateAreaEntity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUseCase)(nil).RegisterUser), operateAreaEntity)
}
